version: '3'
services:
  app:
    build:
      context: .
    ports:
      - 8080:8080
    environment:
      PGHOST: postgres
      PGPORT: 5432
      PGUSER: postgres
      PGDATABASE: postgres
      GRAPHQL_SCHEMA_FILE: /app/schema.graphql
    depends_on:
      - postgres
    healthcheck:
      test: [ "CMD", "nc", "-zv", "localhost", "8080"]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always
  postgres:
    image: postgres:10.4-alpine
    ports:
      - 5432:5432
    volumes:
      - ./sql:/docker-entrypoint-initdb.d
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      interval: 10s
      timeout: 5s
      retries: 3
    restart: always